### ISSUE TITLE
Failed to create mob

### ISSUE THREAD

**Issue by LoboMetalurgico** [TeamAOF/All-of-Fabric-7#122]
[16:53:31] [Server thread/WARN]: Failed to create mob
java.lang.IllegalArgumentException: Duplicate id value for 20!
        at net.minecraft.class_2945.method_12784(class_2945.java:81) ~[server-intermediary.jar:?]
        at net.lightglow.common.entity.DesertedSkeleton.method_5693(DesertedSkeleton.java:56) ~[skeletalremains-1.4.2.jar:?]
        at net.minecraft.class_1297.<init>(class_1297.java:297) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.<init>(class_1309.java:246) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.<init>(class_1308.java:133) ~[server-intermediary.jar:?]
        at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_1588.<init>(class_1588.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_1547.<init>(class_1547.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_1613.<init>(class_1613.java:27) ~[server-intermediary.jar:?]
        at net.lightglow.common.entity.DesertedSkeleton.<init>(DesertedSkeleton.java:38) ~[skeletalremains-1.4.2.jar:?]
        at net.minecraft.class_1299.method_5883(class_1299.java:544) ~[server-intermediary.jar:?]
        at net.minecraft.class_1948.method_24931(class_1948.java:355) ~[server-intermediary.jar:?]
        at net.minecraft.class_1948.method_24930(class_1948.java:285) ~[server-intermediary.jar:?]
        at net.minecraft.class_1948.method_8663(class_1948.java:213) ~[server-intermediary.jar:?]
        at net.minecraft.class_1948.method_27821(class_1948.java:201) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:379) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:333) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by SubordinalBlue** [comment]
WARN level messages not too bad... I'd guess it's the Skeletal Remain's mod having a problem. Have you checked their issues?

**Comment by SubordinalBlue** [comment]
Closing as outdated.

If this is still a current problem for you, please post a comment below.
