### ISSUE TITLE
[Server] Disabling Network Compression causes the server to be impossible to join (Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4656750 into 3)

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#13]
Log:
```
[23:36:46] [User Authenticator #1/INFO]: UUID of player SiriusBYT is 58fbbd04-c2ae-4b1c-976b-48f44d71a958
[23:36:49] [Server thread/INFO]: SiriusBYT[/192.168.1.2:54552] logged in with entity id 76 at (963.5, 86.0, 8901.5)
[23:36:50] [Server thread/INFO]: Sending server config values to client
[23:36:51] [Server thread/INFO]: Server sent config handshake for geode_plus to SiriusBYT
[23:36:51] [Server thread/INFO]: Server sent config handshake for paragon to SiriusBYT
[23:36:52] [Server thread/INFO]: Using Fabric Permissions API
[23:36:53] [Server thread/INFO]: SiriusBYT joined the game
[23:36:56] [Netty Epoll Server IO #1/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:220) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:212) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
	at net.minecraft.class_2552.method_10840(class_2552.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_2552.encode(class_2552.java:8) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
	... 26 more
[23:36:56] [Server thread/INFO]: [STDOUT]: Finalizing energy block registration
[23:36:56] [Server thread/INFO]: SiriusBYT lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
[23:36:56] [Server thread/INFO]: SiriusBYT left the game
[23:36:56] [Server thread/INFO]: Disconnecting client SiriusBYT
[23:37:08] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 11954ms or 239 ticks behind
```

**Comment by Linguardium** [comment]
can you try enabling debugPrintMessages in the connectivity config file?

**Comment by SiriusBYT** [comment]
> can you try enabling debugPrintMessages in the connectivity config file?

[latest.log](https://github.com/TeamAOF/All-of-Fabric-7/files/12445168/latest.log)

**Comment by Linguardium** [comment]
awesome!

looks like an issue with the tag list being too long...

**Comment by SiriusBYT** [comment]
Well then I guess for now setting the network compression to 65535 for now will do.

**Comment by Trent2087** [comment]
Is there a specific reason you want to change this setting? I have never needed to change this.

**Comment by Linguardium** [comment]
in places where network bandwidth is unlimited ( local LAN for instance ) compression is only extra work on the part of the server and clients. no need to compress and decompress in a high bandwidth unsaturated network.

**Comment by SiriusBYT** [comment]
> in places where network bandwidth is unlimited ( local LAN for instance ) compression is only extra work on the part of the server and clients. no need to compress and decompress in a high bandwidth unsaturated network.

Exactly, for instance, my home server running the AOF7 server is awfully underpowered CPU wise, I absolutely need the least overhead possible, as for hosting directly on the client, it's stupid in my case because I only have 8GB of RAM (yes I should seriously buy more) and despite having a top of the line CPU and GPU, due to RAM limitations it's an absolute nightmare, thus the need for a second computer that sure, is less powerful and thus required the least overhead.
It seems like setting the network compression to like 65535 or something is a good enough workaround.

**Comment by TonimatasDEV** [comment]
> Log:
> 
> ```
> [23:36:46] [User Authenticator #1/INFO]: UUID of player SiriusBYT is 58fbbd04-c2ae-4b1c-976b-48f44d71a958
> [23:36:49] [Server thread/INFO]: SiriusBYT[/192.168.1.2:54552] logged in with entity id 76 at (963.5, 86.0, 8901.5)
> [23:36:50] [Server thread/INFO]: Sending server config values to client
> [23:36:51] [Server thread/INFO]: Server sent config handshake for geode_plus to SiriusBYT
> [23:36:51] [Server thread/INFO]: Server sent config handshake for paragon to SiriusBYT
> [23:36:52] [Server thread/INFO]: Using Fabric Permissions API
> [23:36:53] [Server thread/INFO]: SiriusBYT joined the game
> [23:36:56] [Netty Epoll Server IO #1/ERROR]: Exception occurred in netty pipeline
> io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
> 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:?]
> 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:?]
> 	at net.minecraft.class_2535.method_36942(class_2535.java:220) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2535.method_10761(class_2535.java:212) ~[server-intermediary.jar:?]
> 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
> 	at net.minecraft.class_2552.method_10840(class_2552.java:18) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2552.encode(class_2552.java:8) ~[server-intermediary.jar:?]
> 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
> 	... 26 more
> [23:36:56] [Server thread/INFO]: [STDOUT]: Finalizing energy block registration
> [23:36:56] [Server thread/INFO]: SiriusBYT lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4656750 into 3
> [23:36:56] [Server thread/INFO]: SiriusBYT left the game
> [23:36:56] [Server thread/INFO]: Disconnecting client SiriusBYT
> [23:37:08] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 11954ms or 239 ticks behind
> ```

Test this dev version of Packet Fixer. If it works, let me know because I have to upload the version to CurseForge and Modrinth

[PacketFixer-fabric-1.1.8-1.20.1.zip](https://github.com/TeamAOF/All-of-Fabric-7/files/12643836/PacketFixer-fabric-1.1.8-1.20.1.zip)
