### ISSUE TITLE
Spectrum Gemstone Backpack equip causes crash and unable to relogin.

### ISSUE THREAD

**Issue by I0u0I** [TeamAOF/All-of-Fabric-7#131]
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because the return value of "dev.mayaqq.spectrumJetpacks.utils.EquipUtils.getJetpack(net.minecraft.class_1657)" is null
	at dev.mayaqq.spectrumJetpacks.renderer.JetpacksTextRenderer.renderJetpackInfo(JetpacksTextRenderer.java:21)
	at dev.mayaqq.spectrumJetpacks.registry.EventRegistry.lambda$register$0(EventRegistry.java:9)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$eko001$fabric-rendering-v1$render(class_329.java:7386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by I0u0I** [comment]
Will check with the server owner I know they added carry on and trade cycling, may have also added NETS

**Comment by Linguardium** [comment]
someone needs to remove the jetpack from your player data and configure nets to not supply extra back slots
