### ISSUE TITLE
Server Installation Script crashes

### ISSUE THREAD

**Issue by ashk0re** [TeamAOF/All-of-Fabric-7#204]
System: Windows 2019 Server Standard
CPU: AMD Ryzen Threadripper 1950X
RAM: 128 GB
Installed Java Version: java 19.0.2 2023-01-17
Server Version: AOF7 V2.0

[13:28:32] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[13:28:32] [INFO]    Minecraft ServerStarter install/launcher jar
[13:28:32] [INFO]    (Created by BloodWorkXGaming with the help of Contributors)
[13:28:32] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[13:28:32] [INFO]
[13:28:32] [INFO]    This jar will launch a Minecraft Forge/Fabric Modded server
[13:28:32] [INFO]
[13:28:32] [INFO]    Github:    https://github.com/TeamAOF/ServerStarter
[13:28:32] [INFO]    Discord:   https://discord.gg/aof
[13:28:32] [INFO]
[13:28:32] [INFO] You are playing All of Fabric 7
[13:28:32] [INFO] Starting to install/launch the server, lean back!
[13:28:32] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[13:28:32] [INFO]
[13:28:32] [INFO] Testing http://example.com.
[13:28:32] [INFO] Reached http://example.com: true
[13:28:32] [INFO] Testing http://google.com.
[13:28:32] [INFO] Reached http://google.com: true
[13:28:32] [INFO] Reached 2 out of 2 IPs.
[13:28:32] [INFO] Attempting to download modpack Zip.
[13:28:33] [INFO] Downloaded the modpack zip file to D:\Server\AOF7_Server\modpack-download.zip
[13:28:42] [INFO] Moved the mods folder
[13:28:42] [INFO] Starting to unzip files.
[13:28:52] [ERROR] Some uncaught error happened.

java.lang.IllegalArgumentException: malformed input off : 47, length : 4
        at java.base/java.lang.String.throwMalformed(String.java:1252)
        at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1178)
        at java.base/java.lang.String.newStringUTF8NoRepl(String.java:741)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2462)
        at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.handleZip(CursePackType.kt:112)
        at atm.bloodworkxgaming.serverstarter.packtype.AbstractZipbasedPackType.installPack(AbstractZipbasedPackType.kt:30)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:160)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:204)
Caused by: java.nio.charset.MalformedInputException: Input length = 4
        ... 12 more

**Comment by SubordinalBlue** [comment]
What version of the server files are you using?
(just checked with latest from repo, and it's working.)

I'm not seeing the current 2.0 server files on CurseForge... but maybe I'm looking in the wrong place. ^^

**Comment by ashk0re** [comment]
I downloaded this one: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-7/files/5185691

**Comment by ashk0re** [comment]
ok, tried the repo now and that works.
Problem solved.

**Comment by ashk0re** [comment]
Problem solved.

**Comment by SubordinalBlue** [comment]
Yeah, that one has a know bug, fixed bug; waiting on CF to publish the update.

You can use the server files from the repo and they will work.
Really only need `serverstarter.bat` (if on Windows), or `serverstarter.sh` (if on a *nix), and `server-setup-config.yaml`.

**Comment by SubordinalBlue** [comment]
Lol, I'm slow responding. Glad you got it sorted. Cheers.
