### ISSUE TITLE
[Bug Report]: TechReborn Quantum Chestplate Fly not working correctly

### ISSUE THREAD

**Issue by Minionflo** [TeamAOF/All-of-Fabric-7#227]
### Modpack Version

2.0.2

### Describe your issue.

When you try flying with the Quantum Chestplate from techreborn the server prints this warning: `[04:33:03] [Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
        at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
        at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
        at net.minecraft.class_3222.handler$fic000$playerabilitylib$checkAbilityConsistency(class_3222.java:23924) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_7355(class_3222.java:1323) ~[server-intermediary.jar:?]
        at techreborn.items.armor.QuantumSuitItem.tickArmor(QuantumSuitItem.java:94) ~[TechReborn-5.8.7.jar:?]
        at net.minecraft.class_1657.handler$gbf01b$reborncore$tick(class_1657.java:39916) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Minionflo

### Additional Info
PlayerAnimationLib (pal) is included with Zenith Attributes which is a dependency for Zenith

### Related Issues
https://github.com/TechReborn/TechReborn/issues/3186
https://github.com/Ladysnake/PlayerAbilityLib/issues/16

**Comment by Minionflo** [comment]
The issue seems to come from the fact that TechReborn doesnt use the PlayerAbilityLib (pal)

**Comment by Minionflo** [comment]
FYI the techreborn issue (https://github.com/TechReborn/TechReborn/issues/3186)

**Comment by broman** [comment]
You can suppress these warnings by modifying config/pal.properties to set alwaysLogTamperWarnings to false:
```
#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Jul 28 07:39:35 CEST 2023
alwaysLogTamperWarnings=false
```

**Comment by Linguardium** [comment]
someone made a fork of tech reborn to fix this (which the official servers are using, but is not included in any pack that players download). I also just made a mod to fix this.

**Comment by Minionflo** [comment]
> You can suppress these warnings by modifying config/pal.properties to set alwaysLogTamperWarnings to false:
> 
> ```
> #PlayerAbilityLib configuration file
> #
> #If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
> #Fri Jul 28 07:39:35 CEST 2023
> alwaysLogTamperWarnings=false
> ```

that only removes the messages in the log but the Quantum Chestplate is still not working

**Comment by Trent2087** [comment]
Add this mod. Will be included in the next update. Thanks Ling!
https://legacy.curseforge.com/minecraft/mc-mods/techreborn-player-ability-lib-compat
