### ISSUE TITLE
[Bug Report]: Ad Astra Oxygen Loader Fluid Transfer conflict

### ISSUE THREAD

**Issue by I0u0I** [TeamAOF/All-of-Fabric-7#231]
### Modpack Version

2.1.2

### Describe your issue.

One of my players has managed to crash the server by attaching a chest full of buckets of water to Ad Astra's Oxygen Loader using an MI item pipe.

Unable to restart server, as it just crashes when Finalizing fluid block registration

```
[20:26:00] [Server thread/INFO]: [STDOUT]: Finalizing fluid block registration
[20:26:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Moving resources between storages
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: An outer transaction is already active on this thread.
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:89) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at earth.terrarium.botarium.fabric.fluid.storage.PlatformFluidItemHandler.extractFluid(PlatformFluidItemHandler.java:51) ~[botarium-fabric-1.20.1-2.3.3.jar:?]
	at earth.terrarium.botarium.common.fluid.FluidApi.moveFluid(FluidApi.java:163) ~[botarium-fabric-1.20.1-2.3.3.jar:?]
	at earth.terrarium.adastra.common.utils.FluidUtils.moveItemToContainer(FluidUtils.java:82) ~[ad_astra-fabric-1.20.1-1.15.18.jar:?]
	at earth.terrarium.adastra.common.blockentities.machines.OxygenLoaderBlockEntity.updateSlots(OxygenLoaderBlockEntity.java:132) ~[ad_astra-fabric-1.20.1-1.15.18.jar:?]
	at earth.terrarium.adastra.common.blockentities.machines.OxygenLoaderBlockEntity.update(OxygenLoaderBlockEntity.java:127) ~[ad_astra-fabric-1.20.1-1.15.18.jar:?]
	at earth.terrarium.adastra.common.blockentities.base.BasicContainer.method_5447(BasicContainer.java:30) ~[ad_astra-fabric-1.20.1-1.15.18.jar:?]
	at net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper.setStack(InventorySlotWrapper.java:63) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.insert(SingleStackStorage.java:125) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper.insert(InventorySlotWrapper.java:81) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.impl.transfer.item.SidedInventorySlotWrapper.insert(SidedInventorySlotWrapper.java:47) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.impl.transfer.item.SidedInventorySlotWrapper.insert(SidedInventorySlotWrapper.java:31) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at aztech.modern_industrialization.util.StorageUtil2$SmarterInventoryStorage.insert(StorageUtil2.java:65) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.util.StorageUtil2$SmarterInventoryStorage.insert(StorageUtil2.java:52) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.item.ItemNetwork.insertTargets(ItemNetwork.java:300) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.item.ItemNetwork$BlacklistAggregate.insert(ItemNetwork.java:285) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.item.ItemNetwork$BlacklistAggregate.insert(ItemNetwork.java:274) ~[Modern-Industrialization-1.8.4.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:67) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:102) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-6e94fb9801b618ac.jar:?]
	at aztech.modern_industrialization.pipes.item.ItemNetwork.doNetworkTransfer(ItemNetwork.java:108) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.item.ItemNetwork.tick(ItemNetwork.java:68) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.tickNetworks(PipeNetworkManager.java:69) ~[Modern-Industrialization-1.8.4.jar:?]
	at aztech.modern_industrialization.pipes.impl.PipeNetworks.lambda$static$2(PipeNetworks.java:111) ~[Modern-Industrialization-1.8.4.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-64bb13225b65065c.jar:?]
	at net.minecraft.class_3218.handler$ddi000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:14240) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:396) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
```

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

ql0u0lp

**Comment by Linguardium** [comment]
Issue with Ad Astra, dev has been made aware and issue was opened on the Ad Astra github already https://github.com/terrarium-earth/Ad-Astra/issues/530
