### ISSUE TITLE
[Bug Report]: Storage controller broken causing dupe bug

### ISSUE THREAD

**Issue by Hapseleg** [TeamAOF/All-of-Fabric-7#255]
### Modpack Version

2.2.2

### Describe your issue.

Hi there,

I'm not sure whats causing it but the first time i placed down a "storage controller" next to a barrel I get this error:

[11:53:49] [Server thread/ERROR]: [WTHIT] Caught unhandled exception : [class mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider$$Lambda$48285/0x000000080527f3a8
player hapseleg] java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.StorageView.isResourceBlank()" because "view" is null
[11:53:49] [Server thread/ERROR]: [WTHIT] java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.StorageView.isResourceBlank()" because "view" is null
	at mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider.addItem(ItemStorageProvider.java:75)
	at mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider.lambda$appendData$0(ItemStorageProvider.java:52)
	at mcp.mobius.waila.access.DataWriter.lambda$send$1(DataWriter.java:81)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at mcp.mobius.waila.access.DataWriter.send(DataWriter.java:75)
	at mcp.mobius.waila.network.Packets.lambda$initServer$10(Packets.java:166)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
If I place a hopper on top of the controller and place a stackable item in the hopper, the item will stay in the hopper and dupe itself into the barrel, if the item is not stackable it will dupe itself one time, then move into the barrel.

i also created an issue on sophisticated storage github even though this is an unofficial port
https://github.com/P3pp3rF1y/SophisticatedStorage/issues/424

![2024-05-24_12 17 33](https://github.com/TeamAOF/All-of-Fabric-7/assets/12915302/81828471-b207-4ea2-8d2c-371b81ccb0f8)
![2024-05-24_12 17 44](https://github.com/TeamAOF/All-of-Fabric-7/assets/12915302/7c3b86b3-9f32-4450-86a4-5dabc2117a99)
![2024-05-24_12 17 49](https://github.com/TeamAOF/All-of-Fabric-7/assets/12915302/5bd8da7d-2267-459f-bb5e-c63af6fe21cc)

### Latest Log

https://gist.github.com/Hapseleg/6df16835e6eee446caf7f343b5acee59

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by SubordinalBlue** [comment]
This is the repo for the fabric port of Sophisticated Storage: https://github.com/Salandora/SophisticatedStorage
