### ISSUE TITLE
[Bug Report]: Crash at launch.  Mod Discovery took too long

### ISSUE THREAD

**Issue by WillTereika** [TeamAOF/All-of-Fabric-7#311]
### Modpack Version

2.5.2

### Describe your issue.

Modpack crashes with error that says mod discovery took to long, gives me some text as how to fix it by adding more time, but does not give me (Not a programmer or coder in any way at all) enough info on HOW to do it.  I just want to fix this.  Thanks.  error message posted below.

Mod discovery took too long!
net.fabricmc.loader.impl.FormattedException: Analyzing the mod folder contents took longer than 60 seconds. This may be caused by unusually slow hardware, pathological antivirus interference or other issues. The timeout can be changed with the system property fabric.debug.discoveryTimeout (-Dfabric.debug.discoveryTimeout=<desired timeout in seconds>).
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:181)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:216)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:193)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Auseawesome** [comment]
What are your specs, are you running off an almost full harddrive, is your AV blocking it? It shouldn't be taking 60 seconds
