### ISSUE TITLE
Shearing Sheep with Dispenser crashes Game

### ISSUE THREAD

**Issue by Semorphim** [TeamAOF/All-of-Fabric-7#40]
Shearing a Sheep with Shears in a Dispenser crashes game.

Singleplayer only gives Error Code -1

Edit: Version is 0.6.3

Server Crash Report says this:

Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because "stack" is null
	at net.minecraft.class_1890.handler$dkb000$indrev$customEnchantProvider(class_1890.java:4521)
	at net.minecraft.class_1890.method_8225(class_1890.java)
	at net.minecraft.class_1472.redirect$hpg000$zenith$bleh(class_1472.java:3043)
	at net.minecraft.class_1472.method_6636(class_1472.java:235)
	at net.minecraft.class_5168.method_27163(class_5168.java:61)
	at net.minecraft.class_5168.method_10135(class_5168.java:29)
	at net.minecraft.class_2347.dispense(class_2347.java:16)
	at net.minecraft.class_2315.method_10012(class_2315.java:90)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by informatJonas** [comment]
our server version is 0.6.2

**Comment by Kazuhiko-Gushiken** [comment]
@informatJonas @Semorphim This seems to have been fixed as I just tested in the latest version.
