### ISSUE TITLE
AE2 Spatial IO not working

### ISSUE THREAD

**Issue by BeckTFT** [TeamAOF/All-of-Fabric-7#49]
[19:00:09] [Server thread/WARN]: Exception:
java.lang.ClassCastException: class party.lemons.taniwha.level.LevelDataManager cannot be cast to class appeng.spatial.SpatialStorageWorldData (party.lemons.taniwha.level.LevelDataManager and appeng.spatial.SpatialStorageWorldData are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @61832929)
        at appeng.spatial.SpatialStoragePlotManager.getWorldData(SpatialStoragePlotManager.java:59) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.spatial.SpatialStoragePlotManager.allocatePlot(SpatialStoragePlotManager.java:74) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.items.storage.SpatialStorageCellItem.doSpatialTransition(SpatialStorageCellItem.java:142) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.blockentity.spatial.SpatialIOPortBlockEntity.lambda$transition$1(SpatialIOPortBlockEntity.java:172) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.api.networking.IManagedGridNode.ifPresent(IManagedGridNode.java:102) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.blockentity.spatial.SpatialIOPortBlockEntity.transition(SpatialIOPortBlockEntity.java:158) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.blockentity.spatial.SpatialIOPortBlockEntity.lambda$new$0(SpatialIOPortBlockEntity.java:52) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.hooks.ticking.TickHandler.processQueue(TickHandler.java:403) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:293) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at appeng.hooks.ticking.TickHandler.lambda$init$1(TickHandler.java:95) ~[appliedenergistics2-fabric-15.0.13.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-21c1963f26916f23.jar:?]
        at net.minecraft.server.MinecraftServer.handler$coa002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7862) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BeckTFT** [comment]
![aof7 spatial io](https://github.com/TeamAOF/All-of-Fabric-7/assets/151962984/915c5c18-d527-4e1d-8adb-8e7f8b103277)

Even a 1x1 cobblestone doesnt work, both on my server, and on my singleplayer world

**Comment by Tauders** [comment]
@BeckTFT  I got the same issue. It is mentioned on https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7453. Could be fixed by updating `Biome Makeover` (I updated to https://modrinth.com/mod/biome-makeover/version/fabric-1.20.1-1.11.4 and it started to work)

**Comment by ImAK9** [comment]
Reopen if still an issue on latest releases
